{% set name = "jupyter-packaging" %}
{% set version = "0.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_packaging-{{ version }}.tar.gz
  sha256: 9d9b2b63b97ffd67a8bc5391c32a421bc415b264a32c99e4d8d8dd31daae9cf4

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python {{ python_min }}
    - pip
    - packaging
    - hatchling
  run:
    - python >={{ python_min }}
    - packaging
    - tomlkit
    - setuptools >=60.2.0
    - wheel
    - deprecation

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyter_packaging


outputs:
  - name: jupyter-packaging
  - name: jupyter_packaging
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("jupyter-packaging", exact=True) }}

about:
  home: https://github.com/jupyter/jupyter-packaging
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Packaging Utilities

  description: |
    Jupyter Packaging Utilities
  dev_url: https://github.com/jupyter/jupyter-packaging

extra:
  recipe-maintainers:
    - blink1073
    - vidartf
    - timkpaine
    - xmnlab
